version = 1

test_patterns = ["tests/test_*"]

exclude_patterns = ["tests/data/"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "flake8"
enabled = true
