formats: [htmlzip]
version: 2
python:
    version: 3.7
    install:
      - requirements: requirements_dev.txt
      - method: pip
        path: .
        extra_requirements:
          - docs
          - graphviz
      - method: setuptools
        path: .
    system_packages: true
